USE fabrica_bee_acai;



CREATE INDEX IDX_USUARIO_STATUS ON usuario (STATUS_USUARIO);

CREATE INDEX IDX_PARCEIRO_TIPO_STATUS ON parceiro_cliente (TIPO_PARCEIRO, STATUS_PARCEIRO);

CREATE INDEX IDX_INSUMO_NOME ON insumo (NOME);

CREATE INDEX IDX_INSUMO_VALIDADE ON insumo (DATA_VALIDADE);

CREATE INDEX IDX_EST_INS_STATUS ON estoque_insumo (STATUS_ESTOQUE);

CREATE INDEX IDX_EMBALAGEM_ESTOQUE ON embalagem (QTD_ESTOQUE, QTD_RESERVADA, ESTOQUE_MINIMO);

CREATE INDEX IDX_PRODUCAO_ETAPA ON producao (ETAPA_ATUAL);

CREATE INDEX IDX_PRODUCAO_FABRICACAO ON producao (DATA_FABRICACAO);

CREATE INDEX IDX_PRODUCAO_VALIDADE ON producao (DATA_VALIDADE);

CREATE INDEX IDX_PRODUTO_VALIDADE ON produto (DATA_VALIDADE);

CREATE INDEX IDX_EST_PROD_STATUS ON estoque_produto (STATUS_ESTOQUE);

CREATE INDEX IDX_DESCARTE_DATA_TIPO ON descarte (DATA, TIPO_PERDA);

CREATE INDEX IDX_MOV_DATA ON mov_financeira (DATA);

CREATE INDEX IDX_MOV_TIPO_DATA ON mov_financeira (TIPO_MOVIMENTACAO, DATA);

CREATE INDEX IDX_COMPRA_DATA ON compra (DATA_COMPRA);

CREATE INDEX IDX_COMPRA_EMBALAGEM_DATA ON compra_embalagem (DATA_COMPRA);

CREATE INDEX IDX_VENDA_DATA ON venda (DATA_VENDA);

CREATE INDEX IDX_PAGAMENTO_DATA ON pagamento_funcionario (DATA_PAGAMENTO);

CREATE INDEX IDX_NOTA_STATUS ON nota_fiscal (STATUS_NOTA);
