USE fabrica_bee_acai;

-- Camada semântica para PCP, estoque e análises.

CREATE OR REPLACE VIEW vw_pcp_producoes AS
SELECT
    p.ID_PRODUCAO,
    p.LOTE,
    p.NOME_PRODUTO,
    p.TAMANHO,
    p.UNIDADE_MEDIDA,
    p.QTD_NO_LOTE,
    p.ETAPA_ATUAL,
    p.DATA_FABRICACAO,
    p.DATA_VALIDADE,
    p.INICIO_RESFRIAMENTO,
    p.FIM_RESFRIAMENTO,
    u.NOME AS RESPONSAVEL,
    e.NOME AS EMBALAGEM,
    e.CAPACIDADE AS CAPACIDADE_EMBALAGEM,
    e.UNIDADE_CAPACIDADE,
    p.QTD_EMBALAGEM_RESERVADA,
    p.EMBALAGEM_BAIXADA
FROM producao p
INNER JOIN usuario u ON u.ID_USUARIO = p.ID_USUARIO
LEFT JOIN embalagem e ON e.ID_EMBALAGEM = p.ID_EMBALAGEM;


CREATE OR REPLACE VIEW vw_estoque_insumos AS
SELECT
    i.ID_INSUMO,
    i.NOME AS INSUMO,
    i.UNIDADE_MEDIDA,
    i.DATA_VALIDADE,
    ei.QTD_ESTOQUE,
    ei.ESTOQUE_MINIMO,
    ei.DATA_ENTRADA,
    CASE
        WHEN i.DATA_VALIDADE IS NOT NULL
         AND i.DATA_VALIDADE < CURDATE() THEN 'Vencido'
        WHEN ei.QTD_ESTOQUE = 0 THEN 'Esgotado'
        WHEN ei.QTD_ESTOQUE <= ei.ESTOQUE_MINIMO THEN 'Atencao'
        ELSE 'Disponivel'
    END AS STATUS_CALCULADO
FROM insumo i
INNER JOIN estoque_insumo ei ON ei.ID_INSUMO = i.ID_INSUMO;


CREATE OR REPLACE VIEW vw_embalagens AS
SELECT
    ID_EMBALAGEM,
    NOME,
    CAPACIDADE,
    UNIDADE_CAPACIDADE,
    QTD_ESTOQUE,
    QTD_RESERVADA,
    QTD_ESTOQUE - QTD_RESERVADA AS QTD_LIVRE,
    ESTOQUE_MINIMO,
    CASE
        WHEN QTD_ESTOQUE - QTD_RESERVADA = 0 THEN 'Esgotado'
        WHEN QTD_ESTOQUE - QTD_RESERVADA <= ESTOQUE_MINIMO THEN 'Atencao'
        ELSE 'Disponivel'
    END AS STATUS_CALCULADO
FROM embalagem;


CREATE OR REPLACE VIEW vw_estoque_produtos AS
SELECT
    pr.ID_PRODUTO,
    p.ID_PRODUCAO,
    p.LOTE,
    p.NOME_PRODUTO,
    p.ETAPA_ATUAL,
    p.DATA_FABRICACAO,
    pr.DATA_VALIDADE,
    pr.PRECO,
    ep.QTD_DISPONIVEL,
    ep.ESTOQUE_MINIMO,
    CASE
        WHEN p.ETAPA_ATUAL = 'Resfriamento' THEN 'Resfriamento'
        WHEN pr.DATA_VALIDADE < CURDATE() THEN 'Vencido'
        WHEN ep.QTD_DISPONIVEL = 0 THEN 'Esgotado'
        WHEN ep.QTD_DISPONIVEL <= ep.ESTOQUE_MINIMO THEN 'Atencao'
        ELSE 'Disponivel'
    END AS STATUS_CALCULADO
FROM produto pr
INNER JOIN producao p ON p.ID_PRODUCAO = pr.ID_PRODUCAO
INNER JOIN estoque_produto ep ON ep.ID_PRODUTO = pr.ID_PRODUTO;


CREATE OR REPLACE VIEW vw_consumo_insumos AS
SELECT
    p.ID_PRODUCAO,
    p.LOTE,
    p.NOME_PRODUTO,
    i.ID_INSUMO,
    i.NOME AS INSUMO,
    ip.QTD_UTILIZADA,
    ip.UNIDADE_UTILIZADA
FROM insumo_producao ip
INNER JOIN producao p ON p.ID_PRODUCAO = ip.ID_PRODUCAO
INNER JOIN insumo i ON i.ID_INSUMO = ip.ID_INSUMO;


CREATE OR REPLACE VIEW vw_movimentacoes_financeiras AS
SELECT
    mf.ID_MOV,
    mf.DATA,
    mf.TIPO_MOVIMENTACAO,
    mf.VALOR,
    mf.DESCRICAO,
    mf.STATUS,
    mf.FORMA_PAGAMENTO,
    mf.QUANTIDADE,
    mf.TIPO_NOTA_FISCAL,
    mf.NUMERO_NOTA_FISCAL,
    pc.NOME AS PARCEIRO,
    u.NOME AS RESPONSAVEL
FROM mov_financeira mf
LEFT JOIN parceiro_cliente pc ON pc.ID_PARCEIRO = mf.ID_PARCEIRO_FK
LEFT JOIN usuario u ON u.ID_USUARIO = mf.ID_USUARIO;


CREATE OR REPLACE VIEW vw_vendas_detalhadas AS
SELECT
    v.ID_VENDA,
    v.DATA_VENDA,
    pc.NOME AS CLIENTE,
    p.NOME_PRODUTO,
    p.LOTE,
    iv.QUANTIDADE,
    iv.VALOR_UNITARIO,
    iv.VALOR_TOTAL_ITEM,
    v.VALOR_TOTAL,
    v.FORMA_PAGAMENTO,
    v.STATUS,
    v.NUM_NOTA_FISCAL,
    u.NOME AS RESPONSAVEL
FROM venda v
INNER JOIN parceiro_cliente pc ON pc.ID_PARCEIRO = v.ID_CLIENTE
INNER JOIN item_venda iv ON iv.ID_VENDA = v.ID_VENDA
INNER JOIN producao p ON p.ID_PRODUCAO = iv.ID_PRODUCAO
INNER JOIN usuario u ON u.ID_USUARIO = v.ID_USUARIO;


CREATE OR REPLACE VIEW vw_perdas AS
SELECT
    d.ID_DESCARTE,
    d.DATA,
    d.TIPO_PERDA,
    d.QUANTIDADE,
    d.MOTIVO,
    i.NOME AS INSUMO,
    p.LOTE,
    p.NOME_PRODUTO,
    u.NOME AS RESPONSAVEL
FROM descarte d
INNER JOIN usuario u ON u.ID_USUARIO = d.ID_USUARIO
LEFT JOIN insumo i ON i.ID_INSUMO = d.ID_INSUMO
LEFT JOIN producao p ON p.ID_PRODUCAO = d.ID_PRODUCAO;


CREATE OR REPLACE VIEW vw_rastreabilidade_lotes AS
SELECT
    p.ID_PRODUCAO,
    p.LOTE,
    p.NOME_PRODUTO,
    p.DATA_FABRICACAO,
    p.DATA_VALIDADE,
    p.ETAPA_ATUAL,
    u.NOME AS RESPONSAVEL,
    COALESCE(ci.INSUMOS_UTILIZADOS, '') AS INSUMOS_UTILIZADOS,
    COALESCE(vd.QUANTIDADE_VENDIDA, 0) AS QUANTIDADE_VENDIDA,
    COALESCE(vd.TOTAL_VENDAS, 0) AS TOTAL_VENDAS,
    COALESCE(pd.QUANTIDADE_PERDIDA, 0) AS QUANTIDADE_PERDIDA
FROM producao p
INNER JOIN usuario u ON u.ID_USUARIO = p.ID_USUARIO
LEFT JOIN (
    SELECT
        ip.ID_PRODUCAO,
        GROUP_CONCAT(
            CONCAT(i.NOME, ': ', ip.QTD_UTILIZADA, ' ', ip.UNIDADE_UTILIZADA)
            ORDER BY i.NOME SEPARATOR '; '
        ) AS INSUMOS_UTILIZADOS
    FROM insumo_producao ip
    INNER JOIN insumo i ON i.ID_INSUMO = ip.ID_INSUMO
    GROUP BY ip.ID_PRODUCAO
) ci ON ci.ID_PRODUCAO = p.ID_PRODUCAO
LEFT JOIN (
    SELECT
        ID_PRODUCAO,
        SUM(QUANTIDADE) AS QUANTIDADE_VENDIDA,
        COUNT(DISTINCT ID_VENDA) AS TOTAL_VENDAS
    FROM item_venda
    GROUP BY ID_PRODUCAO
) vd ON vd.ID_PRODUCAO = p.ID_PRODUCAO
LEFT JOIN (
    SELECT
        ID_PRODUCAO,
        SUM(QUANTIDADE) AS QUANTIDADE_PERDIDA
    FROM descarte
    WHERE ID_PRODUCAO IS NOT NULL
    GROUP BY ID_PRODUCAO
) pd ON pd.ID_PRODUCAO = p.ID_PRODUCAO;
