USE fabrica_bee_acai;


-- CONSULTAS ANALÍTICAS: PCP, ESTOQUE, COMERCIAL E FINANCEIRO


-- Lotes por etapa do PCP
SELECT
    ETAPA_ATUAL,
    COUNT(*) AS TOTAL_LOTES,
    SUM(QTD_NO_LOTE) AS QUANTIDADE_PLANEJADA_PRODUZIDA
FROM producao
GROUP BY ETAPA_ATUAL
ORDER BY TOTAL_LOTES DESC;


-- Produção mensal
SELECT
    DATE_FORMAT(DATA_FABRICACAO, '%Y-%m') AS MES,
    COUNT(*) AS LOTES,
    SUM(QTD_NO_LOTE) AS QUANTIDADE_PRODUZIDA
FROM producao
GROUP BY DATE_FORMAT(DATA_FABRICACAO, '%Y-%m')
ORDER BY MES;


-- Lotes em resfriamento
SELECT
    LOTE,
    NOME_PRODUTO,
    QTD_NO_LOTE,
    INICIO_RESFRIAMENTO,
    FIM_RESFRIAMENTO,
    GREATEST(TIMESTAMPDIFF(MINUTE, NOW(), FIM_RESFRIAMENTO), 0) AS MINUTOS_RESTANTES
FROM producao
WHERE ETAPA_ATUAL = 'Resfriamento'
ORDER BY FIM_RESFRIAMENTO;


-- Consumo de insumos por lote
SELECT
    p.LOTE,
    p.NOME_PRODUTO,
    i.NOME AS INSUMO,
    ip.QTD_UTILIZADA,
    ip.UNIDADE_UTILIZADA
FROM insumo_producao ip
INNER JOIN producao p ON p.ID_PRODUCAO = ip.ID_PRODUCAO
INNER JOIN insumo i ON i.ID_INSUMO = ip.ID_INSUMO
ORDER BY p.DATA_FABRICACAO DESC, p.LOTE, i.NOME;


-- Consumo acumulado por produto
SELECT
    p.NOME_PRODUTO,
    i.NOME AS INSUMO,
    SUM(ip.QTD_UTILIZADA) AS TOTAL_CONSUMIDO,
    ip.UNIDADE_UTILIZADA
FROM insumo_producao ip
INNER JOIN producao p ON p.ID_PRODUCAO = ip.ID_PRODUCAO
INNER JOIN insumo i ON i.ID_INSUMO = ip.ID_INSUMO
GROUP BY p.NOME_PRODUTO, i.ID_INSUMO, i.NOME, ip.UNIDADE_UTILIZADA
ORDER BY p.NOME_PRODUTO, TOTAL_CONSUMIDO DESC;


-- Insumos abaixo do mínimo
SELECT
    i.NOME,
    ei.QTD_ESTOQUE,
    ei.ESTOQUE_MINIMO,
    i.UNIDADE_MEDIDA,
    GREATEST(ei.ESTOQUE_MINIMO - ei.QTD_ESTOQUE, 0) AS NECESSIDADE_REPOSICAO
FROM estoque_insumo ei
INNER JOIN insumo i ON i.ID_INSUMO = ei.ID_INSUMO
WHERE ei.QTD_ESTOQUE <= ei.ESTOQUE_MINIMO
ORDER BY NECESSIDADE_REPOSICAO DESC;


-- Embalagens: físico, reservado e livre
SELECT
    NOME,
    CAPACIDADE,
    UNIDADE_CAPACIDADE,
    QTD_ESTOQUE,
    QTD_RESERVADA,
    QTD_ESTOQUE - QTD_RESERVADA AS QTD_LIVRE,
    ESTOQUE_MINIMO
FROM embalagem
ORDER BY QTD_LIVRE;


-- Produtos próximos do vencimento
SELECT
    p.NOME_PRODUTO,
    p.LOTE,
    pr.DATA_VALIDADE,
    ep.QTD_DISPONIVEL,
    DATEDIFF(pr.DATA_VALIDADE, CURDATE()) AS DIAS_PARA_VENCER
FROM produto pr
INNER JOIN producao p ON p.ID_PRODUCAO = pr.ID_PRODUCAO
INNER JOIN estoque_produto ep ON ep.ID_PRODUTO = pr.ID_PRODUTO
WHERE pr.DATA_VALIDADE BETWEEN CURDATE() AND DATE_ADD(CURDATE(), INTERVAL 30 DAY)
ORDER BY pr.DATA_VALIDADE;


-- Produtos mais vendidos
SELECT
    p.NOME_PRODUTO,
    SUM(iv.QUANTIDADE) AS QUANTIDADE_VENDIDA,
    SUM(iv.VALOR_TOTAL_ITEM) AS FATURAMENTO
FROM item_venda iv
INNER JOIN producao p ON p.ID_PRODUCAO = iv.ID_PRODUCAO
GROUP BY p.NOME_PRODUTO
ORDER BY QUANTIDADE_VENDIDA DESC;


-- Vendas por cliente
SELECT
    pc.NOME AS CLIENTE,
    COUNT(DISTINCT v.ID_VENDA) AS TOTAL_VENDAS,
    SUM(v.QUANTIDADE) AS QUANTIDADE,
    SUM(v.VALOR_TOTAL) AS FATURAMENTO
FROM venda v
INNER JOIN parceiro_cliente pc ON pc.ID_PARCEIRO = v.ID_CLIENTE
GROUP BY pc.ID_PARCEIRO, pc.NOME
ORDER BY FATURAMENTO DESC;


-- Ticket médio
SELECT
    COUNT(*) AS TOTAL_VENDAS,
    COALESCE(SUM(VALOR_TOTAL), 0) AS FATURAMENTO,
    COALESCE(AVG(VALOR_TOTAL), 0) AS TICKET_MEDIO
FROM venda;


-- Compras de insumos por fornecedor
SELECT
    pc.NOME AS FORNECEDOR,
    COUNT(*) AS COMPRAS,
    SUM(c.QUANTIDADE) AS QUANTIDADE,
    SUM(c.VALOR_TOTAL) AS VALOR_TOTAL
FROM compra c
INNER JOIN parceiro_cliente pc ON pc.ID_PARCEIRO = c.ID_FORNECEDOR
GROUP BY pc.ID_PARCEIRO, pc.NOME
ORDER BY VALOR_TOTAL DESC;


-- Compras de embalagens por fornecedor
SELECT
    pc.NOME AS FORNECEDOR,
    e.NOME AS EMBALAGEM,
    SUM(ce.QUANTIDADE) AS QUANTIDADE,
    SUM(ce.VALOR_TOTAL) AS VALOR_TOTAL
FROM compra_embalagem ce
INNER JOIN parceiro_cliente pc ON pc.ID_PARCEIRO = ce.ID_FORNECEDOR
INNER JOIN embalagem e ON e.ID_EMBALAGEM = ce.ID_EMBALAGEM
GROUP BY pc.ID_PARCEIRO, pc.NOME, e.ID_EMBALAGEM, e.NOME
ORDER BY VALOR_TOTAL DESC;


-- Resultado financeiro mensal
SELECT
    DATE_FORMAT(DATA, '%Y-%m') AS MES,
    SUM(CASE WHEN TIPO_MOVIMENTACAO = 'Entrada' THEN VALOR ELSE 0 END) AS ENTRADAS,
    SUM(CASE WHEN TIPO_MOVIMENTACAO = 'Saida' THEN VALOR ELSE 0 END) AS SAIDAS,
    SUM(CASE WHEN TIPO_MOVIMENTACAO = 'Entrada' THEN VALOR ELSE -VALOR END) AS RESULTADO
FROM mov_financeira
GROUP BY DATE_FORMAT(DATA, '%Y-%m')
ORDER BY MES;


-- Composição das saídas
SELECT
    CATEGORIA,
    COUNT(*) AS MOVIMENTACOES,
    SUM(VALOR) AS TOTAL
FROM (
    SELECT
        mf.ID_MOV,
        mf.VALOR,
        CASE
            WHEN c.ID_COMPRA IS NOT NULL THEN 'Compra de insumo'
            WHEN ce.ID_COMPRA_EMBALAGEM IS NOT NULL THEN 'Compra de embalagem'
            WHEN pf.ID_PAGAMENTO IS NOT NULL THEN 'Pagamento de funcionario'
            ELSE 'Outras saidas'
        END AS CATEGORIA
    FROM mov_financeira mf
    LEFT JOIN compra c ON c.ID_MOV = mf.ID_MOV
    LEFT JOIN compra_embalagem ce ON ce.ID_MOV = mf.ID_MOV
    LEFT JOIN pagamento_funcionario pf ON pf.ID_MOV = mf.ID_MOV
    WHERE mf.TIPO_MOVIMENTACAO = 'Saida'
) x
GROUP BY CATEGORIA
ORDER BY TOTAL DESC;


-- Perdas por tipo
SELECT
    TIPO_PERDA,
    COUNT(*) AS OCORRENCIAS,
    SUM(QUANTIDADE) AS QUANTIDADE_TOTAL
FROM descarte
GROUP BY TIPO_PERDA
ORDER BY QUANTIDADE_TOTAL DESC;


-- Motivos de perda
SELECT
    TIPO_PERDA,
    MOTIVO,
    COUNT(*) AS OCORRENCIAS,
    SUM(QUANTIDADE) AS QUANTIDADE_TOTAL
FROM descarte
GROUP BY TIPO_PERDA, MOTIVO
ORDER BY QUANTIDADE_TOTAL DESC;


-- Perdas por lote
SELECT
    p.NOME_PRODUTO,
    p.LOTE,
    d.TIPO_PERDA,
    SUM(d.QUANTIDADE) AS QUANTIDADE_PERDIDA
FROM descarte d
INNER JOIN producao p ON p.ID_PRODUCAO = d.ID_PRODUCAO
GROUP BY p.ID_PRODUCAO, p.NOME_PRODUTO, p.LOTE, d.TIPO_PERDA
ORDER BY QUANTIDADE_PERDIDA DESC;


-- Saldo teórico por lote
SELECT
    p.LOTE,
    p.NOME_PRODUTO,
    p.QTD_NO_LOTE AS PRODUZIDO,
    COALESCE(v.VENDIDO, 0) AS VENDIDO,
    COALESCE(d.PERDIDO, 0) AS PERDIDO,
    p.QTD_NO_LOTE - COALESCE(v.VENDIDO, 0) - COALESCE(d.PERDIDO, 0) AS SALDO_TEORICO
FROM producao p
LEFT JOIN (
    SELECT ID_PRODUCAO, SUM(QUANTIDADE) AS VENDIDO
    FROM item_venda
    GROUP BY ID_PRODUCAO
) v ON v.ID_PRODUCAO = p.ID_PRODUCAO
LEFT JOIN (
    SELECT ID_PRODUCAO, SUM(QUANTIDADE) AS PERDIDO
    FROM descarte
    WHERE ID_PRODUCAO IS NOT NULL
    GROUP BY ID_PRODUCAO
) d ON d.ID_PRODUCAO = p.ID_PRODUCAO
ORDER BY p.DATA_FABRICACAO DESC;


-- Resumo executivo do período completo
SELECT
    (SELECT COUNT(*) FROM producao) AS LOTES,
    (SELECT COALESCE(SUM(QTD_NO_LOTE), 0) FROM producao) AS TOTAL_PRODUZIDO,
    (SELECT COALESCE(SUM(QTD_ESTOQUE), 0) FROM estoque_insumo) AS ESTOQUE_INSUMOS,
    (SELECT COALESCE(SUM(QTD_DISPONIVEL), 0) FROM estoque_produto) AS ESTOQUE_PRODUTOS,
    (SELECT COALESCE(SUM(QTD_ESTOQUE - QTD_RESERVADA), 0) FROM embalagem) AS EMBALAGENS_LIVRES,
    (
        SELECT COALESCE(SUM(
            CASE WHEN TIPO_MOVIMENTACAO = 'Entrada' THEN VALOR ELSE -VALOR END
        ), 0)
        FROM mov_financeira
    ) AS RESULTADO_FINANCEIRO,
    (SELECT COUNT(*) FROM descarte) AS REGISTROS_DE_PERDA;
