
CREATE DATABASE IF NOT EXISTS fabrica_bee_acai
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE fabrica_bee_acai;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;


-- CADASTROS E ACESSO

CREATE TABLE usuario (
  ID_USUARIO INT UNSIGNED AUTO_INCREMENT,
  NOME VARCHAR(120) NOT NULL,
  CPF VARCHAR(14) NOT NULL,
  EMAIL VARCHAR(120) NOT NULL,
  FOTO_PERFIL VARCHAR(255) NULL,
  CARGO VARCHAR(80) NULL,
  SENHA VARCHAR(255) NOT NULL,
  NIVEL_ACESSO VARCHAR(20) NOT NULL DEFAULT 'Colaborador',
  STATUS_USUARIO VARCHAR(20) NOT NULL DEFAULT 'Ativo',
  TOKEN_RECUP VARCHAR(255) NULL,
  DATA_EXP_TOKEN DATETIME NULL,
  TEMA VARCHAR(10) NOT NULL DEFAULT 'light',
  DATA_CADASTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO),
  CONSTRAINT UK_USUARIO_CPF UNIQUE (CPF),
  CONSTRAINT UK_USUARIO_EMAIL UNIQUE (EMAIL),
  CONSTRAINT CK_USUARIO_NIVEL
    CHECK (NIVEL_ACESSO IN ('Admin', 'Colaborador')),
  CONSTRAINT CK_USUARIO_STATUS
    CHECK (STATUS_USUARIO IN ('Ativo', 'Desativado')),
  CONSTRAINT CK_USUARIO_TEMA
    CHECK (TEMA IN ('light', 'dark'))
) ENGINE=InnoDB;



CREATE TABLE parceiro_cliente (
  ID_PARCEIRO INT UNSIGNED AUTO_INCREMENT,
  NOME VARCHAR(120) NOT NULL,
  CNPJ VARCHAR(18) NULL,
  CPF_CNPJ VARCHAR(18) NULL,
  CONTATO VARCHAR(120) NOT NULL DEFAULT '',
  EMAIL VARCHAR(160) NULL,
  TIPO_PARCEIRO VARCHAR(20) NOT NULL DEFAULT 'Ambos',
  STATUS_PARCEIRO VARCHAR(20) NOT NULL DEFAULT 'Ativo',
  CEP VARCHAR(9) NULL,
  LOGRADOURO VARCHAR(160) NULL,
  NUMERO VARCHAR(20) NULL,
  COMPLEMENTO VARCHAR(80) NULL,
  BAIRRO VARCHAR(100) NULL,
  CODIGO_MUNICIPIO VARCHAR(7) NULL,
  MUNICIPIO VARCHAR(100) NULL,
  UF CHAR(2) NULL,
  DATA_CADASTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT PK_PARCEIRO_CLIENTE PRIMARY KEY (ID_PARCEIRO),
  CONSTRAINT UK_PARCEIRO_CNPJ UNIQUE (CNPJ),
  CONSTRAINT CK_PARCEIRO_TIPO
    CHECK (TIPO_PARCEIRO IN ('Cliente', 'Fornecedor', 'Ambos')),
  CONSTRAINT CK_PARCEIRO_STATUS
    CHECK (STATUS_PARCEIRO IN ('Ativo', 'Desativado')),
  CONSTRAINT CK_PARCEIRO_UF
    CHECK (UF IS NULL OR CHAR_LENGTH(UF) = 2)
) ENGINE=InnoDB;




-- INSUMOS, EMBALAGENS E ESTOQUE

CREATE TABLE insumo (
  ID_INSUMO INT UNSIGNED AUTO_INCREMENT,
  NOME VARCHAR(120) NOT NULL,
  QTD_ESTOQUE DECIMAL(12,3) NOT NULL DEFAULT 0,
  ESTOQUE_MINIMO DECIMAL(12,3) NOT NULL DEFAULT 10,
  UNIDADE_MEDIDA VARCHAR(10) NOT NULL,
  DATA_VALIDADE DATE NULL,

  CONSTRAINT PK_INSUMO PRIMARY KEY (ID_INSUMO),
  CONSTRAINT CK_INSUMO_QTD CHECK (QTD_ESTOQUE >= 0),
  CONSTRAINT CK_INSUMO_MINIMO CHECK (ESTOQUE_MINIMO >= 0),
  CONSTRAINT CK_INSUMO_UNIDADE
    CHECK (UNIDADE_MEDIDA IN ('UN', 'KG', 'G', 'L', 'ML'))
) ENGINE=InnoDB;


CREATE TABLE estoque_insumo (
  ID_ESTOQUE_INSUMO INT UNSIGNED AUTO_INCREMENT,
  ID_INSUMO INT UNSIGNED NOT NULL,
  QTD_ESTOQUE DECIMAL(12,3) NOT NULL DEFAULT 0,
  ESTOQUE_MINIMO DECIMAL(12,3) NOT NULL DEFAULT 10,
  STATUS_ESTOQUE VARCHAR(20) NOT NULL DEFAULT 'Disponivel',
  DATA_ENTRADA DATE NOT NULL DEFAULT (CURRENT_DATE),

  CONSTRAINT PK_ESTOQUE_INSUMO PRIMARY KEY (ID_ESTOQUE_INSUMO),
  CONSTRAINT UK_ESTOQUE_INSUMO UNIQUE (ID_INSUMO),
  CONSTRAINT CK_EST_INS_QTD CHECK (QTD_ESTOQUE >= 0),
  CONSTRAINT CK_EST_INS_MIN CHECK (ESTOQUE_MINIMO >= 0),
  CONSTRAINT CK_EST_INS_STATUS
    CHECK (STATUS_ESTOQUE IN ('Disponivel', 'Atencao', 'Esgotado', 'Vencido')),
  CONSTRAINT FK_EST_INS_INSUMO
    FOREIGN KEY (ID_INSUMO)
    REFERENCES insumo (ID_INSUMO)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=InnoDB;


CREATE TABLE embalagem (
  ID_EMBALAGEM INT UNSIGNED AUTO_INCREMENT,
  NOME VARCHAR(100) NOT NULL,
  CAPACIDADE DECIMAL(12,3) NOT NULL,
  UNIDADE_CAPACIDADE VARCHAR(10) NOT NULL,
  UNIDADE_MEDIDA VARCHAR(10) NOT NULL DEFAULT 'UN',
  QTD_ESTOQUE DECIMAL(12,3) NOT NULL DEFAULT 0,
  QTD_RESERVADA DECIMAL(12,3) NOT NULL DEFAULT 0,
  ESTOQUE_MINIMO DECIMAL(12,3) NOT NULL DEFAULT 10,

  CONSTRAINT PK_EMBALAGEM PRIMARY KEY (ID_EMBALAGEM),
  CONSTRAINT UK_EMBALAGEM_CAPACIDADE
    UNIQUE (NOME, CAPACIDADE, UNIDADE_CAPACIDADE),
  CONSTRAINT CK_EMBALAGEM_CAPACIDADE CHECK (CAPACIDADE > 0),
  CONSTRAINT CK_EMBALAGEM_UNIDADE_CAP
    CHECK (UNIDADE_CAPACIDADE IN ('UN', 'KG', 'G', 'L', 'ML')),
  CONSTRAINT CK_EMBALAGEM_UNIDADE_MEDIDA
    CHECK (UNIDADE_MEDIDA = 'UN'),
  CONSTRAINT CK_EMBALAGEM_QTD CHECK (QTD_ESTOQUE >= 0),
  CONSTRAINT CK_EMBALAGEM_RESERVADA
    CHECK (QTD_RESERVADA >= 0 AND QTD_RESERVADA <= QTD_ESTOQUE),
  CONSTRAINT CK_EMBALAGEM_MINIMO CHECK (ESTOQUE_MINIMO >= 0)
) ENGINE=InnoDB;




-- PRODUCAO, PRODUTOS ACABADOS E DESCARTES

CREATE TABLE producao (
  ID_PRODUCAO INT UNSIGNED AUTO_INCREMENT,
  NOME_PRODUTO VARCHAR(120) NOT NULL,
  TAMANHO DECIMAL(12,3) NOT NULL,
  UNIDADE_MEDIDA VARCHAR(10) NOT NULL,
  LOTE VARCHAR(50) NOT NULL,
  QTD_NO_LOTE DECIMAL(12,3) NOT NULL,
  ETAPA_ATUAL VARCHAR(30) NOT NULL DEFAULT 'Preparacao',
  TEMPO_RESFRIAMENTO_HORAS INT NULL,
  INICIO_RESFRIAMENTO DATETIME NULL,
  FIM_RESFRIAMENTO DATETIME NULL,
  NOTIFICADO_RESFRIAMENTO TINYINT(1) NOT NULL DEFAULT 0,
  DATA_FABRICACAO DATE NOT NULL,
  DATA_VALIDADE DATE NULL,
  ID_USUARIO INT UNSIGNED NOT NULL,
  ID_EMBALAGEM INT UNSIGNED NULL,
  QTD_EMBALAGEM_RESERVADA DECIMAL(12,3) NOT NULL DEFAULT 0,
  EMBALAGEM_BAIXADA TINYINT(1) NOT NULL DEFAULT 0,

  CONSTRAINT PK_PRODUCAO PRIMARY KEY (ID_PRODUCAO),
  CONSTRAINT UK_PRODUCAO_LOTE UNIQUE (LOTE),
  CONSTRAINT CK_PRODUCAO_TAMANHO CHECK (TAMANHO > 0),
  CONSTRAINT CK_PRODUCAO_QTD CHECK (QTD_NO_LOTE > 0),
  CONSTRAINT CK_PRODUCAO_UNIDADE
    CHECK (UNIDADE_MEDIDA IN ('UN', 'KG', 'G', 'L', 'ML')),
  CONSTRAINT CK_PRODUCAO_ETAPA
    CHECK (ETAPA_ATUAL IN (
      'Preparacao', 'Batimento', 'Embalagem',
      'Resfriamento', 'Liberado', 'Descartado'
    )),
  CONSTRAINT CK_PRODUCAO_TEMPO
    CHECK (
      TEMPO_RESFRIAMENTO_HORAS IS NULL
      OR TEMPO_RESFRIAMENTO_HORAS > 0
    ),
  CONSTRAINT CK_PRODUCAO_NOTIFICADO
    CHECK (NOTIFICADO_RESFRIAMENTO IN (0, 1)),
  CONSTRAINT CK_PRODUCAO_EMBALAGEM_RESERVADA
    CHECK (QTD_EMBALAGEM_RESERVADA >= 0),
  CONSTRAINT CK_PRODUCAO_EMBALAGEM_BAIXADA
    CHECK (EMBALAGEM_BAIXADA IN (0, 1)),
  CONSTRAINT FK_PRODUCAO_USUARIO
    FOREIGN KEY (ID_USUARIO)
    REFERENCES usuario (ID_USUARIO)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT FK_PRODUCAO_EMBALAGEM
    FOREIGN KEY (ID_EMBALAGEM)
    REFERENCES embalagem (ID_EMBALAGEM)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=InnoDB;


CREATE TABLE insumo_producao (
  ID_PRODUCAO INT UNSIGNED NOT NULL,
  ID_INSUMO INT UNSIGNED NOT NULL,
  QTD_UTILIZADA DECIMAL(12,3) NOT NULL,
  UNIDADE_UTILIZADA VARCHAR(10) NOT NULL,

  CONSTRAINT PK_INSUMO_PRODUCAO
    PRIMARY KEY (ID_PRODUCAO, ID_INSUMO),
  CONSTRAINT CK_INS_PROD_QTD CHECK (QTD_UTILIZADA > 0),
  CONSTRAINT CK_INS_PROD_UNIDADE
    CHECK (UNIDADE_UTILIZADA IN ('UN', 'KG', 'G', 'L', 'ML')),
  CONSTRAINT FK_IP_PRODUCAO
    FOREIGN KEY (ID_PRODUCAO)
    REFERENCES producao (ID_PRODUCAO)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT FK_IP_INSUMO
    FOREIGN KEY (ID_INSUMO)
    REFERENCES insumo (ID_INSUMO)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=InnoDB;


CREATE TABLE produto (
  ID_PRODUTO INT UNSIGNED AUTO_INCREMENT,
  PRECO DECIMAL(12,2) NOT NULL DEFAULT 0,
  LOTE_DISPONIVEL VARCHAR(50) NOT NULL,
  QTD_DISPONIVEL DECIMAL(12,3) NOT NULL DEFAULT 0,
  ESTOQUE_MINIMO DECIMAL(12,3) NOT NULL DEFAULT 10,
  DATA_VALIDADE DATE NOT NULL,
  ID_PRODUCAO INT UNSIGNED NOT NULL,
  NCM VARCHAR(8) NULL,
  CFOP VARCHAR(4) NULL,
  ORIGEM_MERCADORIA CHAR(1) NOT NULL DEFAULT '0',
  CSOSN VARCHAR(4) NULL,
  CST_ICMS VARCHAR(3) NULL,
  CEST VARCHAR(7) NULL,
  UNIDADE_TRIBUTAVEL VARCHAR(6) NOT NULL DEFAULT 'UN',
  ALIQUOTA_ICMS DECIMAL(7,4) NOT NULL DEFAULT 0,
  ALIQUOTA_PIS DECIMAL(7,4) NOT NULL DEFAULT 0,
  ALIQUOTA_COFINS DECIMAL(7,4) NOT NULL DEFAULT 0,

  CONSTRAINT PK_PRODUTO PRIMARY KEY (ID_PRODUTO),
  CONSTRAINT UK_PRODUTO_PRODUCAO UNIQUE (ID_PRODUCAO),
  CONSTRAINT CK_PRODUTO_PRECO CHECK (PRECO >= 0),
  CONSTRAINT CK_PRODUTO_QTD CHECK (QTD_DISPONIVEL >= 0),
  CONSTRAINT CK_PRODUTO_MIN CHECK (ESTOQUE_MINIMO >= 0),
  CONSTRAINT CK_PRODUTO_ORIGEM
    CHECK (ORIGEM_MERCADORIA IN ('0','1','2','3','4','5','6','7','8')),
  CONSTRAINT CK_PRODUTO_ALIQUOTA_ICMS CHECK (ALIQUOTA_ICMS >= 0),
  CONSTRAINT CK_PRODUTO_ALIQUOTA_PIS CHECK (ALIQUOTA_PIS >= 0),
  CONSTRAINT CK_PRODUTO_ALIQUOTA_COFINS CHECK (ALIQUOTA_COFINS >= 0),
  CONSTRAINT FK_PRODUTO_PRODUCAO
    FOREIGN KEY (ID_PRODUCAO)
    REFERENCES producao (ID_PRODUCAO)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=InnoDB;


CREATE TABLE estoque_produto (
  ID_ESTOQUE_PRODUTO INT UNSIGNED AUTO_INCREMENT,
  ID_PRODUTO INT UNSIGNED NOT NULL,
  QTD_DISPONIVEL DECIMAL(12,3) NOT NULL DEFAULT 0,
  ESTOQUE_MINIMO DECIMAL(12,3) NOT NULL DEFAULT 10,
  STATUS_ESTOQUE VARCHAR(20) NOT NULL DEFAULT 'Disponivel',
  DATA_ENTRADA DATE NOT NULL DEFAULT (CURRENT_DATE),

  CONSTRAINT PK_ESTOQUE_PRODUTO PRIMARY KEY (ID_ESTOQUE_PRODUTO),
  CONSTRAINT UK_ESTOQUE_PRODUTO UNIQUE (ID_PRODUTO),
  CONSTRAINT CK_EST_PROD_QTD CHECK (QTD_DISPONIVEL >= 0),
  CONSTRAINT CK_EST_PROD_MIN CHECK (ESTOQUE_MINIMO >= 0),
  CONSTRAINT CK_EST_PROD_STATUS
    CHECK (STATUS_ESTOQUE IN (
      'Disponivel', 'Atencao', 'Resfriamento',
      'Esgotado', 'Vencido'
    )),
  CONSTRAINT FK_EST_PROD_PRODUTO
    FOREIGN KEY (ID_PRODUTO)
    REFERENCES produto (ID_PRODUTO)
    ON UPDATE CASCADE
    ON DELETE CASCADE
) ENGINE=InnoDB;


CREATE TABLE descarte (
  ID_DESCARTE INT UNSIGNED AUTO_INCREMENT,
  DATA DATE NOT NULL,
  QUANTIDADE DECIMAL(12,3) NOT NULL,
  MOTIVO VARCHAR(255) NOT NULL,
  TIPO_PERDA VARCHAR(30) NOT NULL,
  ID_USUARIO INT UNSIGNED NOT NULL,
  ID_INSUMO INT UNSIGNED NULL,
  ID_PRODUCAO INT UNSIGNED NULL,

  CONSTRAINT PK_DESCARTE PRIMARY KEY (ID_DESCARTE),
  CONSTRAINT CK_DESCARTE_QTD CHECK (QUANTIDADE > 0),
  CONSTRAINT CK_DESCARTE_TIPO
    CHECK (TIPO_PERDA IN ('Refugo', 'Descarte', 'Perda de Insumo')),
  CONSTRAINT FK_DESCARTE_USUARIO
    FOREIGN KEY (ID_USUARIO)
    REFERENCES usuario (ID_USUARIO)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT FK_DESCARTE_INSUMO
    FOREIGN KEY (ID_INSUMO)
    REFERENCES insumo (ID_INSUMO)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT FK_DESCARTE_PRODUCAO
    FOREIGN KEY (ID_PRODUCAO)
    REFERENCES producao (ID_PRODUCAO)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=InnoDB;



-- FINANCEIRO, COMPRAS E VENDAS

CREATE TABLE mov_financeira (
  ID_MOV INT UNSIGNED AUTO_INCREMENT,
  TIPO_MOVIMENTACAO VARCHAR(20) NOT NULL,
  VALOR DECIMAL(12,2) NOT NULL,
  DATA DATE NOT NULL,
  DESCRICAO TEXT NULL,
  STATUS VARCHAR(30) NULL,
  FORMA_PAGAMENTO VARCHAR(50) NULL,
  ID_PARCEIRO_FK INT UNSIGNED NULL,
  ID_USUARIO INT UNSIGNED NULL,
  QUANTIDADE DECIMAL(12,3) NULL,
  TIPO_NOTA_FISCAL VARCHAR(30) NULL,
  NUMERO_NOTA_FISCAL VARCHAR(50) NULL,
  ANEXO_NOTA_FISCAL VARCHAR(255) NULL,
  OBSERVACAO TEXT NULL,

  CONSTRAINT PK_MOV_FINANCEIRA PRIMARY KEY (ID_MOV),
  CONSTRAINT CK_MOV_TIPO
    CHECK (TIPO_MOVIMENTACAO IN ('Entrada', 'Saida')),
  CONSTRAINT CK_MOV_VALOR CHECK (VALOR >= 0),
  CONSTRAINT CK_MOV_QUANTIDADE
    CHECK (QUANTIDADE IS NULL OR QUANTIDADE >= 0),
  CONSTRAINT FK_MOV_PARCEIRO
    FOREIGN KEY (ID_PARCEIRO_FK)
    REFERENCES parceiro_cliente (ID_PARCEIRO)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT FK_MOV_USUARIO
    FOREIGN KEY (ID_USUARIO)
    REFERENCES usuario (ID_USUARIO)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=InnoDB;


CREATE TABLE compra (
  ID_COMPRA INT UNSIGNED AUTO_INCREMENT,
  DATA_COMPRA DATE NOT NULL,
  DATA_VALIDADE DATE NULL,
  QUANTIDADE DECIMAL(12,3) NOT NULL,
  VALOR_TOTAL DECIMAL(12,2) NOT NULL,
  NUM_NOTA_FISCAL VARCHAR(50) NULL,
  ANEXO_NOTA VARCHAR(255) NULL,
  ID_FORNECEDOR INT UNSIGNED NOT NULL,
  ID_INSUMO INT UNSIGNED NOT NULL,
  ID_MOV INT UNSIGNED NOT NULL,

  CONSTRAINT PK_COMPRA PRIMARY KEY (ID_COMPRA),
  CONSTRAINT CK_COMPRA_QTD CHECK (QUANTIDADE > 0),
  CONSTRAINT CK_COMPRA_VALOR CHECK (VALOR_TOTAL >= 0),
  CONSTRAINT FK_COMPRA_FORNECEDOR
    FOREIGN KEY (ID_FORNECEDOR)
    REFERENCES parceiro_cliente (ID_PARCEIRO)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT FK_COMPRA_INSUMO
    FOREIGN KEY (ID_INSUMO)
    REFERENCES insumo (ID_INSUMO)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT FK_COMPRA_MOV
    FOREIGN KEY (ID_MOV)
    REFERENCES mov_financeira (ID_MOV)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=InnoDB;


CREATE TABLE compra_embalagem (
  ID_COMPRA_EMBALAGEM INT UNSIGNED AUTO_INCREMENT,
  DATA_COMPRA DATE NOT NULL,
  QUANTIDADE DECIMAL(12,3) NOT NULL,
  VALOR_TOTAL DECIMAL(12,2) NOT NULL,
  NUM_NOTA_FISCAL VARCHAR(50) NULL,
  ANEXO_NOTA VARCHAR(255) NULL,
  ID_FORNECEDOR INT UNSIGNED NOT NULL,
  ID_EMBALAGEM INT UNSIGNED NOT NULL,
  ID_MOV INT UNSIGNED NOT NULL,

  CONSTRAINT PK_COMPRA_EMBALAGEM PRIMARY KEY (ID_COMPRA_EMBALAGEM),
  CONSTRAINT CK_COMPRA_EMBALAGEM_QTD CHECK (QUANTIDADE > 0),
  CONSTRAINT CK_COMPRA_EMBALAGEM_VALOR CHECK (VALOR_TOTAL >= 0),
  CONSTRAINT FK_CE_FORNECEDOR
    FOREIGN KEY (ID_FORNECEDOR)
    REFERENCES parceiro_cliente (ID_PARCEIRO)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT FK_CE_EMBALAGEM
    FOREIGN KEY (ID_EMBALAGEM)
    REFERENCES embalagem (ID_EMBALAGEM)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT FK_CE_MOV
    FOREIGN KEY (ID_MOV)
    REFERENCES mov_financeira (ID_MOV)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=InnoDB;


CREATE TABLE venda (
  ID_VENDA INT UNSIGNED AUTO_INCREMENT,
  DATA_VENDA DATE NOT NULL,
  QUANTIDADE DECIMAL(12,3) NOT NULL DEFAULT 0,
  VALOR_TOTAL DECIMAL(12,2) NOT NULL,
  FORMA_PAGAMENTO VARCHAR(50) NULL,
  STATUS VARCHAR(30) NULL,
  TIPO_NOTA_FISCAL VARCHAR(30) NULL,
  NUM_NOTA_FISCAL VARCHAR(50) NULL,
  ANEXO_NOTA VARCHAR(255) NULL,
  ID_USUARIO INT UNSIGNED NOT NULL,
  ID_CLIENTE INT UNSIGNED NOT NULL,
  ID_MOV INT UNSIGNED NOT NULL,

  CONSTRAINT PK_VENDA PRIMARY KEY (ID_VENDA),
  CONSTRAINT CK_VENDA_QTD CHECK (QUANTIDADE >= 0),
  CONSTRAINT CK_VENDA_VALOR CHECK (VALOR_TOTAL >= 0),
  CONSTRAINT FK_VENDA_USUARIO
    FOREIGN KEY (ID_USUARIO)
    REFERENCES usuario (ID_USUARIO)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT FK_VENDA_CLIENTE
    FOREIGN KEY (ID_CLIENTE)
    REFERENCES parceiro_cliente (ID_PARCEIRO)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT FK_VENDA_MOV
    FOREIGN KEY (ID_MOV)
    REFERENCES mov_financeira (ID_MOV)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=InnoDB;


CREATE TABLE item_venda (
  ID_ITEM_VENDA INT UNSIGNED AUTO_INCREMENT,
  QUANTIDADE DECIMAL(12,3) NOT NULL,
  VALOR_UNITARIO DECIMAL(12,2) NOT NULL,
  VALOR_TOTAL_ITEM DECIMAL(12,2) NOT NULL,
  ID_VENDA INT UNSIGNED NOT NULL,
  ID_PRODUTO INT UNSIGNED NOT NULL,
  ID_PRODUCAO INT UNSIGNED NOT NULL,

  CONSTRAINT PK_ITEM_VENDA PRIMARY KEY (ID_ITEM_VENDA),
  CONSTRAINT CK_ITEM_VENDA_QTD CHECK (QUANTIDADE > 0),
  CONSTRAINT CK_ITEM_VENDA_UNIT CHECK (VALOR_UNITARIO >= 0),
  CONSTRAINT CK_ITEM_VENDA_TOTAL CHECK (VALOR_TOTAL_ITEM >= 0),
  CONSTRAINT FK_ITEM_VENDA_VENDA
    FOREIGN KEY (ID_VENDA)
    REFERENCES venda (ID_VENDA)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT FK_ITEM_VENDA_PRODUTO
    FOREIGN KEY (ID_PRODUTO)
    REFERENCES produto (ID_PRODUTO)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT FK_ITEM_VENDA_PRODUCAO
    FOREIGN KEY (ID_PRODUCAO)
    REFERENCES producao (ID_PRODUCAO)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=InnoDB;


CREATE TABLE pagamento_funcionario (
  ID_PAGAMENTO INT UNSIGNED AUTO_INCREMENT,
  MES_REFERENCIA VARCHAR(7) NOT NULL,
  VALOR_PAGO DECIMAL(12,2) NOT NULL,
  DATA_PAGAMENTO DATE NOT NULL,
  DESCRICAO TEXT NULL,
  COMPROVANTE VARCHAR(255) NULL,
  ID_USUARIO INT UNSIGNED NOT NULL,
  ID_MOV INT UNSIGNED NOT NULL,

  CONSTRAINT PK_PAGAMENTO_FUNCIONARIO PRIMARY KEY (ID_PAGAMENTO),
  CONSTRAINT CK_PAGAMENTO_VALOR CHECK (VALOR_PAGO >= 0),
  CONSTRAINT FK_PAGAMENTO_USUARIO
    FOREIGN KEY (ID_USUARIO)
    REFERENCES usuario (ID_USUARIO)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT FK_PAGAMENTO_MOV
    FOREIGN KEY (ID_MOV)
    REFERENCES mov_financeira (ID_MOV)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=InnoDB;




-- EMISSAO FISCAL

CREATE TABLE emissao_fiscal_config (
  ID_CONFIG INT UNSIGNED AUTO_INCREMENT,
  PROVEDOR VARCHAR(60) NOT NULL DEFAULT 'Nuvem Fiscal',
  STATUS_CONFIG VARCHAR(40) NOT NULL DEFAULT 'Nao configurado',
  AMBIENTE VARCHAR(20) NOT NULL DEFAULT 'Homologacao',
  CLIENT_ID VARCHAR(255) NULL,
  CLIENT_SECRET_CRIPT LONGTEXT NULL,
  CNPJ VARCHAR(14) NULL,
  ESCOPO VARCHAR(160) NOT NULL DEFAULT 'empresa nfe nfce',
  ULTIMO_TESTE DATETIME NULL,
  ULTIMO_ERRO TEXT NULL,
  DATA_ATUALIZACAO DATETIME NULL,

  CONSTRAINT PK_EMISSAO_FISCAL_CONFIG PRIMARY KEY (ID_CONFIG),
  CONSTRAINT CK_FISCAL_AMBIENTE
    CHECK (AMBIENTE IN ('Homologacao', 'Producao'))
) ENGINE=InnoDB;


CREATE TABLE nota_fiscal (
  ID_NOTA INT UNSIGNED AUTO_INCREMENT,
  ID_VENDA INT UNSIGNED NOT NULL,
  MODELO VARCHAR(4) NOT NULL,
  STATUS_NOTA VARCHAR(30) NOT NULL DEFAULT 'Rascunho',
  ID_PROVEDOR VARCHAR(100) NULL,
  NUMERO VARCHAR(30) NULL,
  SERIE VARCHAR(10) NULL,
  CHAVE_ACESSO VARCHAR(60) NULL,
  PROTOCOLO VARCHAR(80) NULL,
  MOTIVO_STATUS TEXT NULL,
  PAYLOAD_JSON LONGTEXT NULL,
  RESPOSTA_JSON LONGTEXT NULL,
  DATA_EMISSAO DATETIME NULL,
  DATA_ATUALIZACAO DATETIME NOT NULL
    DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,

  CONSTRAINT PK_NOTA_FISCAL PRIMARY KEY (ID_NOTA),
  CONSTRAINT UK_NOTA_VENDA_MODELO UNIQUE (ID_VENDA, MODELO),
  CONSTRAINT UK_NOTA_CHAVE_ACESSO UNIQUE (CHAVE_ACESSO),
  CONSTRAINT CK_NOTA_MODELO CHECK (MODELO IN ('55', '65')),
  CONSTRAINT CK_NOTA_STATUS
    CHECK (STATUS_NOTA IN (
      'Rascunho', 'Processando', 'Autorizada',
      'Rejeitada', 'Cancelada'
    )),
  CONSTRAINT FK_NOTA_VENDA
    FOREIGN KEY (ID_VENDA)
    REFERENCES venda (ID_VENDA)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=InnoDB;



SET FOREIGN_KEY_CHECKS = 1;



